name: nexai
description: NexAI - A beautiful OpenAI client with Material Design 3
publish_to: 'none'
version: 1.1.6-ead3a42a4+185

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
    # 图标
  font_awesome_flutter: ^10.12.0
  # material_design_icons_flutter: ^7.0.7296
  material_design_icons_flutter:
    git:
      url: https://github.com/bggRGjQaUbCoE/material_design_icons_flutter.git
      ref: const
  # toast
  flutter_smart_dialog: ^4.9.8+5
    # 加密
  crypto: ^3.0.6
  encrypt: ^5.0.3
    # 视频播放器
  media_kit: ^1.2.6 # Primary package.
  media_kit_video: ^1.3.1 # For video rendering.
  media_kit_libs_video: ^1.0.7
  # 高帧率
  flutter_displaymode: ^0.7.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.4
  flutter_math_fork: '>=0.7.4'
  gpt_markdown: ^1.1.5
  provider: ^6.1.5
  google_fonts: ^8.0.2
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  dynamic_color: '>=1.8.1'
  fluent_ui: ^4.14.0
  package_info_plus: '>=9.0.0'
  device_info_plus: ^12.3.0
  v_video_compressor: ^2.0.0
  file_picker: ^10.3.10
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0078D4"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
